apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-crud-deployment
spec:
  selector:
    matchLabels:
      app: springboot-k8s-mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: springboot-k8s-mysql
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: springboot-crud-k8s
        image: sarantiya18/springboot-k8:1.0
        ports:
        - containerPort: 8080
        env:   # Setting Enviornmental Variables from configmap
        - name: DB_HOST   
          valueFrom :
            configMapKeyRef :
              name : db-config
              key :  host

        - name: Database_name 
          valueFrom :
            configMapKeyRef :
              name : db-config
              key :  Name

        - name: DB_USERNAME  
          valueFrom :
            secretKeyRef :
              name : mysqlsecret
              key :  username

        - name: DB_PASSWORD
          valueFrom :
            secretKeyRef :
              name : mysqlsecret
              key :  password

---
apiVersion: v1 #K8 api version
kind: Service 
metadata: #
  name: springboot-crud-svc
spec:
  selector:
    app: springboot-k8s-mysql
  ports:
  - protocol: "TCP"
    port: 8080 # The port that the service is running on in the cluster
    targetPort: 8080 # The port exposed by the service
  type: NodePort # type of the service.
