kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name: admin-role-pod-admin
rules:
 - apiGroups: ["*"]
   resources: ["pods"]
   verbs: ["create", "list", "get", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-secrets-global
subjects:
- kind: User
  name: ansadmin
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin-role-pod-admin 
  apiGroup: rbac.authorization.k8s.io
